### ISSUE TITLE
Get by column content

### ISSUE THREAD

**Issue by aitorvs** [SimonVT/schematic#35]
I am new to schematic and I can't figure this one out just looking at the source code. How could I create an InexactContentUri such that I can get table elements using a 'selection' type like "LIKE ?" and the corresponding selection arguments?

...and thanks a lot for this great project.

**Comment by MyDogTom** [comment]
I would say you cannot use `like ?` directly in `InexactContentUri` because `whereColumn` always uses `= ?` condition and `where` do not use `pathSegments`.
But you can easily achieve this just by providing correct `selection` and `selectionArgs` to ContentResolver's `query` method.
Something like this: `context.getContentResolver().query(URI, null, COLUMN + " LIKE ?", new String[]{VALUE}, null);`

**Comment by aitorvs** [comment]
that what I ended up doing eventually.

thanks a lot

**Comment by SimonVT** [comment]
`@InexactContentUri` is for when you want to query based on a value in the Uri, e.g. by querying an ID.
With `LIKE` it makes more sense to create the selection yourself, as @MyDogTom said :)
